# Generated by Django 5.1.5 on 2025-02-02 16:35

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("owner_name", models.CharField(max_length=255)),
                ("business_location", models.CharField(max_length=255)),
                (
                    "type_of_business",
                    models.CharField(
                        choices=[
                            ("Importer", "Importer"),
                            ("Trader", "Trader"),
                            ("Both", "Both"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "dealing_with",
                    models.CharField(
                        choices=[
                            ("Laptops", "Laptops"),
                            ("Spare Parts", "Spare Parts"),
                            ("Both", "Both"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "business_name_board_photo",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="business_photos"
                    ),
                ),
                (
                    "authorized_person_photo",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="authorized_person_photos"
                    ),
                ),
                ("mobile_number", models.CharField(max_length=15)),
                ("is_approved", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "businuss_details",
            },
        ),
    ]
