# Generated by Django 5.1.5 on 2025-01-28 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("owner_name", models.CharField(max_length=255)),
                ("authorized_person_name", models.CharField(max_length=255)),
                ("business_location", models.CharField(max_length=255)),
                (
                    "type_of_business",
                    models.CharField(
                        choices=[
                            ("Importer", "Importer"),
                            ("Trader", "Trader"),
                            ("Both", "Both"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "dealing_with",
                    models.CharField(
                        choices=[
                            ("Laptops", "Laptops"),
                            ("Spare Parts", "Spare Parts"),
                            ("Both", "Both"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "business_name_board_photo",
                    models.ImageField(upload_to="business_photos/"),
                ),
                (
                    "authorized_person_photo",
                    models.ImageField(upload_to="authorized_person_photos/"),
                ),
                ("mobile_number", models.CharField(max_length=15)),
                ("email_id", models.EmailField(max_length=254)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
