# Generated by Django 5.1.5 on 2025-01-29 12:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessregistration",
            name="authorized_person_photo",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="authorized_person_photos"
            ),
        ),
        migrations.AlterField(
            model_name="businessregistration",
            name="business_name_board_photo",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="business_photos"
            ),
        ),
    ]
