# Generated by Django 5.1.5 on 2025-02-02 16:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="businessdetails",
            name="created",
        ),
        migrations.RemoveField(
            model_name="businessdetails",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="businessdetails",
            name="updated",
        ),
        migrations.RemoveField(
            model_name="businessdetails",
            name="updated_by",
        ),
    ]
