# Generated by Django 5.1.5 on 2025-01-29 14:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "business",
            "0002_alter_businessregistration_authorized_person_photo_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BusinessRegistration",
            new_name="BusinessDetails",
        ),
        migrations.AlterModelTable(
            name="businessdetails",
            table="businuss_details",
        ),
    ]
