# Generated by Django 5.1.5 on 2025-01-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0003_rename_businessregistration_businessdetails_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="businessdetails",
            name="authorized_person_name",
        ),
        migrations.RemoveField(
            model_name="businessdetails",
            name="email_id",
        ),
        migrations.AlterField(
            model_name="businessdetails",
            name="address",
            field=models.CharField(max_length=255),
        ),
    ]
