# Generated by Django 5.1.5 on 2025-02-02 16:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0003_businessdetails_approved_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="businessdetails",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="businessdetails",
            name="updated_at",
        ),
    ]
