# Generated by Django 5.1.5 on 2025-01-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0004_remove_businessdetails_authorized_person_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessdetails",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
