# Generated by Django 5.1.4 on 2025-01-28 16:10

import catalog.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAttributes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attribute_name", models.CharField(max_length=250, unique=True)),
                ("is_default", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "product_attributes",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=250)),
                ("category_group_id", models.IntegerField(default=0)),
                (
                    "image_url",
                    models.ImageField(
                        blank=True, null=True, upload_to=catalog.models.rename_image
                    ),
                ),
                (
                    "image_alt_tag",
                    models.CharField(blank=True, max_length=160, null=True),
                ),
                (
                    "image_title",
                    models.CharField(blank=True, max_length=160, null=True),
                ),
                (
                    "canonical_url",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_column="parent_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="catalog.category",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        db_column="updated_by",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "category",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=250)),
                ("short_description", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "canonical_url",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_enabled", models.BooleanField(default=True)),
                ("is_best_seller", models.BooleanField(default=False)),
                ("is_home_featured", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pc_category",
                        to="catalog.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "product",
            },
        ),
        migrations.CreateModel(
            name="ProductAttributeValue",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("attribute_value", models.CharField(max_length=200)),
                ("order_no", models.IntegerField(blank=True, default=1, null=True)),
                (
                    "attribute",
                    models.ForeignKey(
                        db_column="attribute_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pa_attr",
                        to="catalog.productattributes",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="p_attr_val",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "db_table": "product_attribute_value",
            },
        ),
        migrations.CreateModel(
            name="ProductBrand",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=250)),
                (
                    "image_url",
                    models.ImageField(
                        blank=True, null=True, upload_to=catalog.models.rename_image
                    ),
                ),
                (
                    "image_alt_tag",
                    models.CharField(blank=True, max_length=160, null=True),
                ),
                (
                    "image_title",
                    models.CharField(blank=True, max_length=160, null=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        db_column="updated_by",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "product_brand",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                db_column="brand_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_brand",
                to="catalog.productbrand",
            ),
        ),
        migrations.CreateModel(
            name="ProductImages",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "full_url",
                    models.ImageField(
                        blank=True, null=True, upload_to=catalog.models.rename_image
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=250, null=True)),
                ("caption", models.CharField(blank=True, max_length=250, null=True)),
                ("order_by", models.IntegerField(blank=True, default=0, null=True)),
                ("is_enabled", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_image",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "db_table": "product_images",
            },
        ),
    ]
