# Generated by Django 5.1.4 on 2025-01-27 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_productbrand_product_productcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImages",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("full_url", models.CharField(max_length=200)),
                ("title", models.CharField(blank=True, max_length=250, null=True)),
                ("caption", models.CharField(blank=True, max_length=250, null=True)),
                ("order_by", models.IntegerField(blank=True, default=0, null=True)),
                ("is_enabled", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_image",
                        to="catalog.product",
                    ),
                ),
            ],
        ),
    ]
