# Generated by Django 5.1.4 on 2025-01-27 09:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_productimages"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="productimages",
            table="product_images",
        ),
    ]
