# Generated by Django 5.1.5 on 2025-01-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_alter_category_image_url_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="is_best_seller",
            new_name="is_approved",
        ),
        migrations.RemoveField(
            model_name="product",
            name="canonical_url",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_featured",
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.CharField(max_length=200),
        ),
    ]
