# Generated by Django 5.1.4 on 2025-01-27 10:08

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_alter_productimages_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimages",
            name="full_url",
            field=models.ImageField(
                blank=True, null=True, upload_to=catalog.models.rename_image
            ),
        ),
    ]
