# Generated by Django 5.1.5 on 2025-01-30 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_rename_is_best_seller_product_is_approved_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productbrand",
            name="image_alt_tag",
        ),
        migrations.RemoveField(
            model_name="productbrand",
            name="image_title",
        ),
        migrations.RemoveField(
            model_name="productbrand",
            name="updated",
        ),
        migrations.RemoveField(
            model_name="productbrand",
            name="updated_by",
        ),
        migrations.AddField(
            model_name="product",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                db_column="brand_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_brand",
                to="catalog.productbrand",
            ),
        ),
    ]
