# Generated by Django 5.1.5 on 2025-01-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_remove_productbrand_image_alt_tag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="other_brand",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
