# Generated by Django 5.1.4 on 2025-01-27 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_alter_productimages_full_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAttributes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attribute_name", models.CharField(max_length=250, unique=True)),
                ("is_default", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "product_attributes",
            },
        ),
        migrations.CreateModel(
            name="ProductPartAttributeValue",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("attribute_value", models.TextField(max_length=255)),
                ("order_no", models.IntegerField(blank=True, default=1, null=True)),
                (
                    "attribute",
                    models.ForeignKey(
                        db_column="attribute_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pa_attr",
                        to="catalog.productattributes",
                    ),
                ),
                (
                    "product_part",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="p_attr_val",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "db_table": "product_attribute_value",
            },
        ),
    ]
