# Generated by Django 5.1.4 on 2025-01-27 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_productattributes_productpartattributevalue"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttributesValues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attributes_values", models.CharField(max_length=200)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_attributes",
                        to="catalog.productattributes",
                    ),
                ),
            ],
            options={
                "db_table": "attributes_values",
            },
        ),
        migrations.CreateModel(
            name="ProductAttributeValue",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("order_no", models.IntegerField(blank=True, default=1, null=True)),
                (
                    "attribute",
                    models.ForeignKey(
                        db_column="attribute_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pa_attr",
                        to="catalog.productattributes",
                    ),
                ),
                (
                    "attribute_value",
                    models.ForeignKey(
                        db_column="attribute_value_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pa_attr_val",
                        to="catalog.attributesvalues",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="p_attr_val",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "db_table": "product_attribute_value",
            },
        ),
        migrations.DeleteModel(
            name="ProductPartAttributeValue",
        ),
    ]
