# Generated by Django 5.1.4 on 2025-01-27 11:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0007_attributesvalues_productattributevalue_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attributesvalues",
            old_name="country",
            new_name="product_attributes",
        ),
    ]
