# Generated by Django 5.1.5 on 2025-02-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0007_remove_category_canonical_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="category_group_id",
        ),
        migrations.AddField(
            model_name="category",
            name="fa_icon_class",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
