# Generated by Django 5.1.4 on 2025-01-27 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0009_delete_productattributevalue"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAttributeValue",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("order_no", models.IntegerField(blank=True, default=1, null=True)),
                (
                    "attribute",
                    models.ForeignKey(
                        db_column="attribute_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pa_attr",
                        to="catalog.productattributes",
                    ),
                ),
                (
                    "attribute_value",
                    models.ForeignKey(
                        db_column="attribute_value_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pa_attr_val",
                        to="catalog.attributesvalues",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="p_attr_val",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "db_table": "product_attribute_value",
            },
        ),
    ]
