# Generated by Django 5.1.4 on 2025-01-28 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0010_productattributevalue"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pc_category",
                to="catalog.category",
            ),
        ),
        migrations.DeleteModel(
            name="ProductCategory",
        ),
    ]
