# Generated by Django 5.1.4 on 2025-01-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0011_product_category_delete_productcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productattributevalue",
            name="attribute_value",
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name="AttributesValues",
        ),
    ]
