# Generated by Django 5.1.4 on 2025-01-28 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0013_alter_product_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="category_group_id",
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                db_column="category_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category",
                to="catalog.category",
            ),
        ),
    ]
