# Generated by Django 5.1.4 on 2025-01-28 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0014_remove_category_category_group_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="category_group_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pc_category",
                to="catalog.category",
            ),
        ),
    ]
